name: 'Deploy Docker Images'
description: 'Deploy application using Docker Compose with specified images'

inputs:
  monolith-image:
    description: 'Docker image for monolith service'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create docker-compose.yml
      shell: bash
      run: |
        cat > docker-compose.yml << EOF
        version: '3.8'

        services:
          monolith:
            image: ${{ inputs.monolith-image }}
            ports:
              - "8080:8080"
            environment:
              - ASPNETCORE_ENVIRONMENT=Production
              - ASPNETCORE_URLS=http://+:8080
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:8080/echo"]
              interval: 10s
              timeout: 5s
              retries: 5
              start_period: 30s
        EOF

    - name: Display docker-compose configuration
      shell: bash
      run: |
        echo "Docker Compose Configuration:"
        cat docker-compose.yml

    - name: Start services
      shell: bash
      run: |
        docker-compose up -d

    - name: Show running containers
      shell: bash
      run: |
        docker-compose ps
        docker-compose logs
